export const fakeConges = [
  {
    id: 1,
    entreprise: { id: 1, name: 'Entreprise 1' },
    employe: { id: 101, name: 'Alice Ben Salem' },
    startDate: '2025-06-01',
    endDate: '2025-06-05',
    type: 'Maladie',
    description: 'Congé pour maladie avec certificat médical',
    justificatifFile: null,
    status: 'justified',
  },
  {
    id: 2,
    entreprise: { id: 1, name: 'Entreprise 1' },
    employe: { id: 102, name: 'Omar Trabelsi' },
    startDate: '2025-06-03',
    endDate: '2025-06-04',
    type: 'Urgence',
    description: 'Congé imprévu pour urgence familiale',
    justificatifFile: null,
    status: 'not justified',
  },
  {
    id: 3,
    entreprise: { id: 2, name: 'Entreprise 2' },
    employe: { id: 103, name: 'Leila Mbarek' },
    startDate: '2025-05-15',
    endDate: '2025-05-20',
    type: 'Vacances',
    description: 'Vacances annuelles approuvées',
    justificatifFile: null,
    status: 'justified',
  },
  {
    id: 4,
    entreprise: { id: 3, name: 'Entreprise 3' },
    employe: { id: 104, name: 'Sami Kacem' },
    startDate: '2025-04-10',
    endDate: '2025-04-12',
    type: 'Personnel',
    description: 'Congé pour raisons personnelles',
    justificatifFile: null,
    status: 'not justified',
  },
  {
    id: 5,
    entreprise: { id: 2, name: 'Entreprise 2' },
    employe: { id: 105, name: 'Nour Mejri' },
    startDate: '2025-06-07',
    endDate: '2025-06-10',
    type: 'Formation',
    description: 'Participation à une formation professionnelle',
    justificatifFile: null,
    status: 'justified',
  },
  {
    id: 6,
    entreprise: { id: 1, name: 'Entreprise 1' },
    employe: { id: 106, name: 'Fares Gharbi' },
    startDate: '2025-06-02',
    endDate: '2025-06-02',
    type: 'Urgence',
    description: 'Absence non signalée',
    justificatifFile: null,
    status: 'not justified',
  },
  {
    id: 7,
    entreprise: { id: 3, name: 'Entreprise 3' },
    employe: { id: 107, name: 'Hana Saidi' },
    startDate: '2025-03-01',
    endDate: '2025-03-10',
    type: 'Maternité',
    description: 'Début du congé maternité',
    justificatifFile: null,
    status: 'justified',
  },
  {
    id: 8,
    entreprise: { id: 2, name: 'Entreprise 2' },
    employe: { id: 108, name: 'Walid Jaziri' },
    startDate: '2025-05-30',
    endDate: '2025-06-04',
    type: 'Vacances',
    description: 'Vacances approuvées par la direction',
    justificatifFile: null,
    status: 'justified',
  },
  {
    id: 9,
    entreprise: { id: 3, name: 'Entreprise 3' },
    employe: { id: 109, name: 'Amel Fekih' },
    startDate: '2025-04-20',
    endDate: '2025-04-22',
    type: 'Maladie',
    description: 'Congé maladie sans justificatif',
    justificatifFile: null,
    status: 'not justified',
  },
  {
    id: 10,
    entreprise: { id: 1, name: 'Entreprise 1' },
    employe: { id: 110, name: 'Youssef Belhaj' },
    startDate: '2025-06-05',
    endDate: '2025-06-08',
    type: 'Vacances',
    description: 'Congé approuvé après période de surcharge',
    justificatifFile: null,
    status: 'justified',
  },
];
