// Mock data for Historique des affiliations mutuelle
export const historiqueData = [
  {
    id: 1,
    date: '2024-11-12',
    employeId: 1,
    employeName: 'Jean Dupont',
    entrepriseId: 1,
    entrepriseName: "Entreprise A",
    paie: 'Novembre 2024',
    action: 'Affiliation',
    details: 'Affilié à la mutuelle santé standard',
  },
  {
    id: 2,
    date: '2024-10-05',
    employeId: 2,
    employeName: 'Marie Martin',
    entrepriseId: 1,
    entrepriseName: "Entreprise A",
    paie: 'Octobre 2024',
    action: 'Désaffiliation',
    details: "Fin de contrat — résiliation de la mutuelle",
  },
  {
    id: 3,
    date: '2024-09-18',
    employeId: 3,
    employeName: 'Luc Bernard',
    entrepriseId: 2,
    entrepriseName: "Entreprise B",
    paie: 'Septembre 2024',
    action: 'Affiliation',
    details: 'Affilié à la mutuelle premium',
  },
  {
    id: 4,
    date: '2024-08-02',
    employeId: 4,
    employeName: 'Sophie Leroy',
    entrepriseId: 2,
    entrepriseName: "Entreprise B",
    paie: 'Août 2024',
    action: 'Modification',
    details: 'Changement de formule — prise en charge étendue',
  },
  {
    id: 5,
    date: '2024-07-30',
    employeId: 5,
    employeName: 'Paul Moreau',
    entrepriseId: 3,
    entrepriseName: "Entreprise C",
    paie: 'Juillet 2024',
    action: 'Affiliation',
    details: 'Affilié — adhésion collective',
  },
];
