// Mock data for primes - Comptable management

export const PRIME_TYPES = [
  { value: 'performance', label: 'Prime de performance' },
  { value: 'annual', label: 'Prime annuelle' },
  { value: 'exceptional', label: 'Prime exceptionnelle' },
  { value: 'seniority', label: 'Prime d\'ancienneté' },
  { value: 'transport', label: 'Prime de transport' },
  { value: 'meal', label: 'Prime de repas' },
  { value: 'holiday', label: 'Prime de vacances' },
  { value: 'thirteenth', label: '13ème mois' },
];

export const PRIME_STATUS = [
  { value: 'pending', label: 'En attente', color: 'warning' },
  { value: 'approved', label: 'Validée', color: 'info' },
  { value: 'rejected', label: 'Refusée', color: 'error' },
  { value: 'paid', label: 'Payée', color: 'success' },
];

export const fakePrimes = [
  {
    id: 1,
    entreprise: { id: 1, name: 'Portorium Consulting' },
    employe: { id: 101, name: 'Alice Ben Salem', poste: 'Développeur Senior' },
    type: 'performance',
    typeLabel: 'Prime de performance',
    amount: 1500.00,
    period: '2026-02',
    description: 'Excellente performance sur le projet Alpha',
    status: 'approved',
    createdAt: '2026-02-10',
    validatedAt: '2026-02-15',
    validatedBy: 'Jean Dupont',
    paidAt: null,
  },
  {
    id: 2,
    entreprise: { id: 1, name: 'Portorium Consulting' },
    employe: { id: 102, name: 'Omar Trabelsi', poste: 'Chef de projet' },
    type: 'exceptional',
    typeLabel: 'Prime exceptionnelle',
    amount: 2000.00,
    period: '2026-02',
    description: 'Livraison anticipée du projet Beta',
    status: 'pending',
    createdAt: '2026-02-18',
    validatedAt: null,
    validatedBy: null,
    paidAt: null,
  },
  {
    id: 3,
    entreprise: { id: 2, name: 'Tech Solutions SARL' },
    employe: { id: 103, name: 'Leila Mbarek', poste: 'Designer UX' },
    type: 'annual',
    typeLabel: 'Prime annuelle',
    amount: 3000.00,
    period: '2026-01',
    description: 'Prime annuelle 2025',
    status: 'paid',
    createdAt: '2026-01-05',
    validatedAt: '2026-01-10',
    validatedBy: 'Marie Martin',
    paidAt: '2026-01-31',
  },
  {
    id: 4,
    entreprise: { id: 2, name: 'Tech Solutions SARL' },
    employe: { id: 104, name: 'Sami Kacem', poste: 'Comptable' },
    type: 'seniority',
    typeLabel: 'Prime d\'ancienneté',
    amount: 500.00,
    period: '2026-02',
    description: '5 ans d\'ancienneté',
    status: 'approved',
    createdAt: '2026-02-01',
    validatedAt: '2026-02-05',
    validatedBy: 'Jean Dupont',
    paidAt: null,
  },
  {
    id: 5,
    entreprise: { id: 1, name: 'Portorium Consulting' },
    employe: { id: 105, name: 'Nour Mejri', poste: 'Analyste RH' },
    type: 'thirteenth',
    typeLabel: '13ème mois',
    amount: 2800.00,
    period: '2025-12',
    description: '13ème mois 2025',
    status: 'paid',
    createdAt: '2025-12-01',
    validatedAt: '2025-12-15',
    validatedBy: 'Marie Martin',
    paidAt: '2025-12-25',
  },
  {
    id: 6,
    entreprise: { id: 3, name: 'Green Energy SA' },
    employe: { id: 106, name: 'Fares Gharbi', poste: 'Technicien' },
    type: 'performance',
    typeLabel: 'Prime de performance',
    amount: 800.00,
    period: '2026-02',
    description: 'Performance Q1 2026',
    status: 'rejected',
    createdAt: '2026-02-12',
    validatedAt: '2026-02-14',
    validatedBy: 'Jean Dupont',
    paidAt: null,
    rejectionReason: 'Objectifs non atteints',
  },
  {
    id: 7,
    entreprise: { id: 3, name: 'Green Energy SA' },
    employe: { id: 107, name: 'Hana Saidi', poste: 'Responsable Commercial' },
    type: 'exceptional',
    typeLabel: 'Prime exceptionnelle',
    amount: 2500.00,
    period: '2026-01',
    description: 'Signature contrat majeur',
    status: 'paid',
    createdAt: '2026-01-20',
    validatedAt: '2026-01-22',
    validatedBy: 'Marie Martin',
    paidAt: '2026-01-31',
  },
  {
    id: 8,
    entreprise: { id: 2, name: 'Tech Solutions SARL' },
    employe: { id: 108, name: 'Walid Jaziri', poste: 'Ingénieur DevOps' },
    type: 'transport',
    typeLabel: 'Prime de transport',
    amount: 150.00,
    period: '2026-02',
    description: 'Prime mensuelle transport',
    status: 'pending',
    createdAt: '2026-02-20',
    validatedAt: null,
    validatedBy: null,
    paidAt: null,
  },
  {
    id: 9,
    entreprise: { id: 1, name: 'Portorium Consulting' },
    employe: { id: 109, name: 'Amel Fekih', poste: 'Assistante Direction' },
    type: 'meal',
    typeLabel: 'Prime de repas',
    amount: 200.00,
    period: '2026-02',
    description: 'Prime mensuelle repas',
    status: 'approved',
    createdAt: '2026-02-01',
    validatedAt: '2026-02-03',
    validatedBy: 'Jean Dupont',
    paidAt: null,
  },
  {
    id: 10,
    entreprise: { id: 3, name: 'Green Energy SA' },
    employe: { id: 110, name: 'Youssef Mansour', poste: 'Directeur Technique' },
    type: 'annual',
    typeLabel: 'Prime annuelle',
    amount: 5000.00,
    period: '2026-01',
    description: 'Prime annuelle direction',
    status: 'paid',
    createdAt: '2026-01-02',
    validatedAt: '2026-01-05',
    validatedBy: 'Marie Martin',
    paidAt: '2026-01-31',
  },
  {
    id: 11,
    entreprise: { id: 1, name: 'Portorium Consulting' },
    employe: { id: 111, name: 'Rania Bouzid', poste: 'Développeur Junior' },
    type: 'performance',
    typeLabel: 'Prime de performance',
    amount: 600.00,
    period: '2026-02',
    description: 'Bonne intégration et progression',
    status: 'pending',
    createdAt: '2026-02-22',
    validatedAt: null,
    validatedBy: null,
    paidAt: null,
  },
  {
    id: 12,
    entreprise: { id: 2, name: 'Tech Solutions SARL' },
    employe: { id: 112, name: 'Karim Belhadj', poste: 'Commercial' },
    type: 'holiday',
    typeLabel: 'Prime de vacances',
    amount: 400.00,
    period: '2026-02',
    description: 'Prime vacances été 2026',
    status: 'pending',
    createdAt: '2026-02-21',
    validatedAt: null,
    validatedBy: null,
    paidAt: null,
  },
];

// Summary statistics for dashboard
export const getPrimesSummary = (primes) => {
  const total = primes.reduce((sum, p) => sum + p.amount, 0);
  const pending = primes.filter((p) => p.status === 'pending');
  const approved = primes.filter((p) => p.status === 'approved');
  const paid = primes.filter((p) => p.status === 'paid');
  const rejected = primes.filter((p) => p.status === 'rejected');

  return {
    totalAmount: total,
    pendingCount: pending.length,
    pendingAmount: pending.reduce((sum, p) => sum + p.amount, 0),
    approvedCount: approved.length,
    approvedAmount: approved.reduce((sum, p) => sum + p.amount, 0),
    paidCount: paid.length,
    paidAmount: paid.reduce((sum, p) => sum + p.amount, 0),
    rejectedCount: rejected.length,
  };
};
